# Generated by Django 4.2.20 on 2025-03-08 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='stock_keeping_unit',
        ),
    ]
