# Generated by Django 4.2.20 on 2025-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_order_price_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='customer_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
