# Generated by Django 4.2.20 on 2025-03-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_users_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('medical', 'Medical'), ('agricultural', 'Agricultural'), ('technology', 'Technology'), ('all', 'All')], default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
