# Generated by Django 4.2.20 on 2025-03-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_supplier_address_remove_supplier_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_keeping_unit',
            field=models.CharField(max_length=100),
        ),
    ]
