# Generated by Django 4.2.20 on 2025-03-28 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_warehouse_category_alter_warehouse_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('electronics', 'Electronics'), ('medical', 'Medical'), ('agricultural', 'Agricultural'), ('technology', 'Technology'), ('all', 'All')], default='all', max_length=50),
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'warehouse_Product',
            },
        ),
    ]
