# Generated by Django 4.2.20 on 2025-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_warehouseproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
