# Generated by Django 4.2.20 on 2025-03-28 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_warehouseproduct_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
