# Generated by Django 4.2.20 on 2025-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_product_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
