# Generated by Django 4.2.20 on 2025-04-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_warehouse_description_alter_warehouse_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('warehouse staff', 'Warehouse Staff'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='sku',
            field=models.CharField(max_length=50),
        ),
    ]
