# Generated by Django 4.2.20 on 2025-04-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_users_role_alter_warehouseproduct_sku'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='WarehouseStaff',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('groceries', 'Groceries'), ('clothing', 'Clothing'), ('medicine', 'Medicine'), ('automotive', 'Automotive'), ('agricultural', 'Agricultural'), ('stationery', 'Stationery'), ('technology', 'Technology'), ('sports_equipment', 'Sports Equipment'), ('general', 'General'), ('all', 'All')], default='all', max_length=50),
        ),
    ]
